### ISSUE TITLE
导致设置 sass.data 无效

### ISSUE THREAD

**Issue by ickg5** [CANntyield/taro-plugin-compiler-optimization#7]
```tsx
{
  // ...
  plugins: [
  'taro-plugin-compiler-optimization'
  ],
  sass: {
    data: "$hd: 1;"
  },
  // ...
}
```
会导致这样：
```scss
$button-medium-height: 44px * $hd;

.medium {
  height: var(--button-medium-height, $button-medium-height);
  // ...
}
```
![1644574689(1)](https://user-images.githubusercontent.com/18252854/153574570-9258d4bb-2993-40cf-bda9-b6340575ba89.png)
